config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get '/guess/:number', to: 'pages#segment'
  get '/counter_views', to: 'pages#counter_views'
  post '/counter_views', to: 'pages#counter_views'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @name = params[:name].upcase
    @number = params[:number].to_i
    @number_to_guess = 36
  end

  def counter_views
    @count = params[:number].to_i + 1
  end

  def segment
    @number = params[:number]
    @number_to_guess = 36
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def guess_number(number, number_to_guess)
    number = number.to_i
    if number <  number_to_guess
      'Your guess is too low.'
    elsif number > number_to_guess
      'Your guess is too high.'
    else
      'Your guess is correct.'
    end
  end

  def begins_with_alphabet(name)
    if name[0] =~ /[^A-Z]/
      "Hey, your name starts with a letter of the alphabet!"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParamsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/counter_views.html.erb
<h1>Counter page</h1>

<p>
  <%= @count %>
</p>

<%= button_to 'Count now', counter_views_path(:number => @count), method: :post %>

app/views/pages/index.html.erb
<h1>Welcome to Params App</h1>

<p><%= begins_with_alphabet(@name) %></p>

<p><%= guess_number(@number, @number_to_guess) %></p>

app/views/pages/segment.html.erb
<h1>Welcome to Segment</h1>

<p><%= guess_number(@number, @number_to_guess) %></p>